[package]
name = "makeit"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
shell-words = "1.1.0"
termint = "0.4.1"
utf8-chars = "3.0.2"
